### ISSUE TITLE
cannot parse nested `:not` or `:hover` and the like correctly

### ISSUE THREAD

**Issue by lzl124631x** [ortic/css2less#17]
```
a {
    :not(a) {
      display: block;
    }
}
```
Result:
```
a {
	*: not(a) { display: block;
}
```

**Comment by lzl124631x** [comment]
as well as, 

```
a {
  a:hover {
    display: block;
  }
}
```
Result:
```
a {
	a: hover { display: block;
}
```
It seems that css2less cannot parse nested `:xxx` correctly.

**Comment by Remo** [comment]
thanks for reporting this, will look into it

**Comment by Remo** [comment]
@lzl124631x the problem with `:not` I agree with, but the second example is invalid. Your example isn't valid CSS, it's no surprise that the result isn't proper less code. That case I've already covered by a test: https://github.com/ortic/css2less/blob/master/tests/Css2LessTest.php#L22

**Comment by Remo** [comment]
The first example isn't a big deal either, the output just isn't nice. If you have a CSS like this:

```css
:not(p) {
    color: blue;
}
```

The result will be this:
```less
@color_1: blue;

&:not(p) {
        color: @color_1;
}
```

There is no need for the `&`, but the code works fine.

**Comment by lzl124631x** [comment]
@Remo  I don't understand why my second example is *invalid*. Maybe a better example can be:
```
div {
  a:active{
    color: red;
  }
}
```
which css2less converts to 
```
div {
	a: active{ color: red;
}
```
This less is invalid (it's short of one `}`). These examples show that -- **any NESTED `:blabla` will be incorrectly handled.**

**Comment by Remo** [comment]
Your input is not valid CSS, you can't nest selectors in CSS

**Comment by lzl124631x** [comment]
Oh, yes. sorry for my stupidity. That's embarrassing. I didn't realize this problem in the legacy code. Thanks @Remo sorry for my disturbing. Good day.

**Comment by Remo** [comment]
No worries, the `:not` part was still helpful
